// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnsynizKjTfv9zLKli6U5-zs6ZCX7huqQ',
    appId: '1:339677477216:android:6b1557cffacc1430694605',
    messagingSenderId: '339677477216',
    projectId: 'fozo-tech',
    storageBucket: 'fozo-tech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT7bvPXaZRN1uEXB7wzTuUz2QVITRix_Q',
    appId: '1:339677477216:ios:8b8512017fef7c79694605',
    messagingSenderId: '339677477216',
    projectId: 'fozo-tech',
    storageBucket: 'fozo-tech.firebasestorage.app',
    iosBundleId: 'com.example.fozoCustomerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7fniCPqvEd1O6L9ixG5gJZ39m4-PvJMs',
    appId: '1:339677477216:web:348e3ef4ea603e4c694605',
    messagingSenderId: '339677477216',
    projectId: 'fozo-tech',
    authDomain: 'fozo-tech.firebaseapp.com',
    storageBucket: 'fozo-tech.firebasestorage.app',
    measurementId: 'G-ZBL7H6H4W7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT7bvPXaZRN1uEXB7wzTuUz2QVITRix_Q',
    appId: '1:339677477216:ios:8b8512017fef7c79694605',
    messagingSenderId: '339677477216',
    projectId: 'fozo-tech',
    storageBucket: 'fozo-tech.firebasestorage.app',
    iosBundleId: 'com.example.fozoCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7fniCPqvEd1O6L9ixG5gJZ39m4-PvJMs',
    appId: '1:339677477216:web:2f8567662affe03e694605',
    messagingSenderId: '339677477216',
    projectId: 'fozo-tech',
    authDomain: 'fozo-tech.firebaseapp.com',
    storageBucket: 'fozo-tech.firebasestorage.app',
    measurementId: 'G-SD5SHBDSES',
  );

}